### PR TITLE
Fix #106

### LINKED ISSUE #106: Warning: incremental compilation (maybe) broken when using `@taylorize` in package
When using `@taylorize` inside a module, a warning appears about incremental compilation "maybe" being "fatally broken". I wasn't able to reproduce the problem when defining a module in the REPL, but figured out the following MWE:

I created the [`MyPkg`](https://github.com/PerezHz/MyPkg) julia package, which uses `@taylorize` to define an ODE. Then, `MyPkg` may be `git clone`'d on an empty folder, and from `MyPkg` root dir start a julia REPL and do:
```julia
# first, in an empty folder do:
# git clone https://github.com/PerezHz/MyPkg
# cd MyPkg
# julia ### open a Julia REPL
# then, in the REPL do:
import Pkg
Pkg.activate(".") # activate environment on MyPkg root dir
using MyPkg # warning appears
```
The warning messages that appear are:
```
[ Info: Precompiling MyPkg [87ba5f82-8271-4dfc-8d8f-dcd99beeaf9d]
WARNING: eval into closed module TaylorIntegration:
:-
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module TaylorIntegration:
:^
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module TaylorIntegration:
typeof(MyPkg.xdot2)()
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module TaylorIntegration:
nothing
  ** incremental compilation may be fatally broken for this module **
```

So far, I've reproduced the error on julia 1.3 and 1.4 locally and on a remote machine.

The incremental compilation warnings appear the first time `MyPkg` is loaded via `using MyPkg`, and do not appear on subsequent loadings, until `MyPkg` is changed internally (e.g., by uncommenting the `MyPkg.greet()` function), and `using MyPkg` is ran again so that the code is re-compiled. Also, as far as I can tell, things seem to work fine (`taylorinteg` works fine, etc.) even when the warnings appear, but I don't know if it's safe to live with these warnings hanging around.

A workaround is to set `__precompile__(false)`, but then `MyPkg` is compiled each time it is loaded, and compilation times may become exceptionally slow (~ 10 min) in some cases where the defined ODE involves many operations.

This issue seems to be related to the use of `eval` in the definition of `@taylorize`, and found a [post in Discourse](https://discourse.julialang.org/t/use-of-eval-in-closed-module-and-incremental-compilation-may-be-broken/30028) which dealt with similar things, but wasn't able to figure out a way to get rid of these warnings so that it's possible to not use `__precompile__(false)`. @lbenet, do you know what might be going on here?

### PR DESCRIPTION
**Pull request by PerezHz**
Since #106 was last closed, I've been able to trace that issue to [this line of code](https://github.com/dfdx/Espresso.jl/blob/76c899cbd19df6f18e10875439591368fbc9b679/src/utils.jl#L151) in Espresso.jl, where the use of `Core.eval` leads to a silent error when using `@taylorize` from inside a module via the use of `ExGraph` [here](https://github.com/PerezHz/TaylorIntegration.jl/blob/1f36a47362bfe4d74022f257d20f5a78b1eea110/src/parse_eqs.jl#L412). For the time being, I have been able to workaround this issue by re-implementing the relevant part of Espresso in TaylorIntegration without using `eval`, but a better solution might be to report this directly there to look for a better solution. So, current changes are not elegant, but they get the job done, as far as I could tell.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks for finding the error? Why there is no manifestation of the error? Do the fix proposed in https://github.com/dfdx/Espresso.jl/issues/49 solves  the problems?

**Comment by PerezHz** [comment]
> Thanks for finding the error? Why there is no manifestation of the error? Do the fix proposed in [dfdx/Espresso.jl#49](https://github.com/dfdx/Espresso.jl/issues/49) solves the problems?

The error happens silently since the call to `ExGraph` is inside a `try ... catch ... end` block; after testing the solution proposed in [dfdx/Espresso.jl#49](https://github.com/dfdx/Espresso.jl/issues/49) it seems to be working without changing the code in `src/parse_eqs.jl`, so it fortunately looks like most of those changes won't be needed once a new Espresso.jl version is released. Still, I think it's important to have this tested, which is what I'm trying to do add now.

**Comment by PerezHz** [comment]
@lbenet, regarding the silent failure, I'm proposing to ditch the `try...catch...end` block which called `ExGraph` in `parse_eqs.jl`: I found it is not needed anymore (i.e., it does not falling back to the `catch` anymore) and instead I think it would be useful to know if a call to `ExGraph` fails for any reason, what do you think? I also added some tests regarding the use of `@taylorize` within Julia packages. Tests are passing with Espresso.jl v0.6.1 (thanks @dfdx!), so after a trip to a famous mythological labyrinth in Minos, this is ready for review...

File: test/TestPkg/src/TestPkg.jl [hunk 1]
```diff
@@ -0,0 +1,183 @@
+module TestPkg
```
Comment (lbenet) [inline test/TestPkg/src/TestPkg.jl:1]: I fully agree to include the tests you have implemented here. I suggest to include few comments (perhaps outside from `TestPkg` simply to describe what you are testing. Our memory is finite and we are prone to forget!

**Review by lbenet — APPROVED** [review]
First of all, thanks for finding out the true problem that was causing #106!

This PR LGTM. I have only added one comment, to add some comments about what `MyPkg` has inside, that we want to test; few lines simply counteracting of finite memory.

**Review by lbenet — APPROVED** [review]
Thanks a lot!

**Comment by lbenet** [comment]
Merging!
